name: CI

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13.5'
      - name: Install dependencies
        run: pip install -r requirements.txt
        working-directory: src
      - name: Check code style with Black
        run: black --check src
        working-directory: src
      - name: Lint with pylint
        run: pylint src --fail-under=8.0 --rcfile=src/.pylintrc
        working-directory: src
      - name: Type check with mypy
        run: mypy src
        working-directory: src
      - name: Unit tests
        run: pytest
        working-directory: src